version: '3.1'

services:

  frontend:
    image: candiddev01/frontend-jwt-prod:v1
    container_name: reactjs-container
#    network: jwt-network
    networks:
      - jwt-network
      - bridge
    depends_on:
      - backend
      - db
    restart: always
    env_file:
      - ./frontend-jwt-auth/.env
    ports:
      - 3001:80
    volumes:
      - frontend:/var/www/html


  backend:
    image: candiddev01/backend-jwt-prod:v1
    container_name: nodejs-container
#   network: jwt-network
    networks:
      - jwt-network
      - bridge
    depends_on:
      - db
    restart: always
    ports:
      - 8080:8080
#    environment:
#      MYSQL_DB_HOST: db
#      MYSQL_DB_USER: exampleuser
#      MYSQL_DB_PASSWORD: examplepass
#      MYSQL_DB_NAME: exampledb
    volumes:
      - backend:/var/www/html

  db:
    image: candiddev01/simple-mysql8-prod:v1
    container_name: mysql-container
#    network: jwt-network
    networks:
      - jwt-network
      - bridge
    restart: always
#    environment:
#      MYSQL_DATABASE: exampledb
#      MYSQL_USER: exampleuser
#      MYSQL_ROOT_PASSWORD: p@ssw0rd
#      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  frontend:
  backend:
  db:

networks: 
  jwt-network:
  bridge:
